### ISSUE TITLE
[InvalidArgumentException] Could not find package - at any version for your minimum-stability

### ISSUE THREAD

**Issue by darrensapalo** [davidpiesse/facebook_messenger_php#1]
Encountering this issue when using the command 

`composer require davidpiesse/facebook_messenger_php`

The full error message is this:

> [InvalidArgumentException] Could not find package davidpiesse/facebook_messenger_php at any version for your minimum-stability (stable). Check the package spelling or your minimum stability.
## Resolution

After some searching, I found a possibly [related issue with composer](https://github.com/composer/composer/issues/3367).

It recommends to append the `=dev-master` at the end of the command, resulting to:

`composer require davidpiesse/facebook_messenger_php=dev-master`

After doing so, the command successfully terminates with the following warning:

> Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

Not sure if that has any adverse effects. I have yet to try it out.

**Comment by darrensapalo** [comment]
![image](https://cloud.githubusercontent.com/assets/2420577/17126451/090a7066-5330-11e6-96ac-5001e7662642.png)

For reference.

**Comment by davidpiesse** [comment]
The current version is dev-master (as it is still very much a work in progress).
To still use this you need to use the "dev-master" version but composer doen't allow this by default.
Add/change a line in your composer.json file

```
"minimum-stability":"dev"
```

As for the second error - the package uses guzzlehttp/guzzle not guzzle/guzzle. So that is an odd one. Do you have guzzle elsewhere in your composer requirements?
