### ISSUE TITLE
You must define a recipient PSID for the message to be sent to

### ISSUE THREAD

**Issue by sahidhossen** [davidpiesse/facebook_messenger_php#3]
I am getting this error when I send the text message.  Here is my code. 
 
 $callback->textMessages()->each(function ($entryMessage) use ( $messenger) {
            $message = $entryMessage->message;
            Log::info('Income-2 ', ['recipient_id' => $entryMessage->recipient_id]);
            $messenger->sendMessage(new TextMessage("This is a basic text message with a maximum length of 320 characters"), $entryMessage->recipient_id);
        });

**Comment by davidpiesse** [comment]
I think the TextMessage object needs the recipientid?

The source code should be explanatory I hope.
Little work has gone into this for a while so I am a bit rusty on its
workings.

**Comment by sahidhossen** [comment]
Can you tell me where you add the $recipient_id in trait MessageTrait? 

Because when you checked the $recipient_id with checkRecipient()  the recipient_id return null.

**Comment by davidpiesse** [comment]
I'll try and look at this later today.

David

On 5 Mar 2017 10:21, "sahidhossen" <notifications@github.com> wrote:

Can you tell me where you add the $recipient_id in trait MessageTrait?

Because when you checked the $recipient_id with checkRecipient() the
recipient_id return null.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/davidpiesse/facebook_messenger_php/issues/3#issuecomment-284218547>,
or mute the thread
